sudo: false
language: node_js
node_js:
  - '10'
branches:
  only:
  - master
services:
- docker
install:
  - npm install
before_script:
- docker-compose -f docker-compose-travis.yml up -d --exit-code-from
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
