version: '2'
services:
  vote-mysql:
    image: devops/vote-mysql:latest
    build: ./mysql
    command: [
            '--default-authentication-plugin=mysql_native_password',
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
    ]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
  vote-redis:
    image: redis:alpine
    restart: always
    ports:
      - '16379:6379'
